# LapierreLab
# Author: Philippe Maisonneuve
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This script calculates light attenuation rates (Kd)
# from data files generated by the PAR-UV probe (Bertolo Lab, UQTR)
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Calibrated data generated by the PAR-UV probe are stored as .csv 
# files in a "CDOM" folder located in a folder "data" which will be
# set as the working drectory
setwd("~/Documents/Lapierre Lab/Maîtrise/Data/2019/PUV/csv")

# Create a list containing the names of all the files in the CDOM folder
data.files = list.files(path = "./")

# Create a matrix to store Kd values, R2, and maximum depth at each site
output = matrix(0,ncol = 3, nrow = length(data.files))
colnames(output) = c("Kd313", "R2.Kd313","Kd320", "R2.Kd320","Kd340", "R2.Kd340","Kd443", "R2.Kd443","Kd550", "R2.Kd550",  "Max_depth")
rownames(output) = data.files[i]

# Set average surface irradiance at each wavelength in μW/(cm^2*nm) 
I0_313 <- 6.7
I0_320 <- 
I0_340 <-
I0_443 <-
I0_550 <- 



for(i in 1:length(data.files))
{
  
  #Import the data
  header <- read.table(paste0(data.files[i]), nrows = 1, header = FALSE, sep =',', stringsAsFactors = FALSE)
  data <- read.table(paste0(data.files[i]), skip = 2, header = FALSE, sep =',')
  colnames(data) <- unlist(header)
  
  #Remove the 100th first and 100th last rows of data to eliminate unstable values
  data <- data[-c(1:100),]
  n<-dim(data)[1]
  data<-data[1:(n-100),]
  
  output[i,1] <- lm(log(5000))
  output[i,2] <- 
  output[i,3] <-
  output[i,4] <-
  
  }